events {}
http {
    upstream api {
        server api-1:8080;
        server api-2:8080;
        server api-3:8080;
    }
    server {
        listen 8080;
        location / {
            proxy_pass http://api;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Correlation-ID $http_x_correlation_id;
            proxy_next_upstream error timeout http_502 http_503;
            proxy_read_timeout 30s;
        }
    }
}
